server:
  port: 8181
  servlet:
    context-path: /identity

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://127.0.0.1:3307/identity_service}
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:16102004}
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: off

jwt:
  signer-key: "4rIPdLH9nyMeUAMuzOBnuOOQbOYNxhdgDACzaxJhgNQoYO/XEhENk7mqakChG/Yr"
  valid-duration: 3600 # 1 hour in seconds
  refreshable-duration: 360000 # 100 hours in seconds

