server:
  port: 8181
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3307/identity_service"
    username: root
    password: 16102004
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: off

jwt:
  signerKey: "4rIPdLH9nyMeUAMuzOBnuOOQbOYNxhdgDACzaxJhgNQoYO/XEhENk7mqakChG/Yr"